### ISSUE TITLE
Multiple hostnames

### ISSUE THREAD

**Issue by Zakay** [grachevko/docker-hosts-updater#2]
Is there a way to do multiple hostnames for one docker?

**Comment by grachevko** [comment]
@Zakay Yeap. Added to readme. 
I also fixed some errors, run `docker pull grachev/docker-hosts-updater` first.

**Comment by Zakay** [comment]
Great, but I'm currently not getting it to work at all.

```
MBP: user$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS               NAMES
c144f4e12f1b        nginx                          "nginx -g 'daemon ..."   About a minute ago   Up About a minute   80/tcp, 443/tcp     compassionate_wiles
3ed82d4ec90b        grachev/docker-hosts-updater   "grachev-dhu"            About a minute ago   Up About a minute                       docker-hosts-updater-test
```

```
MBP: user$ docker run -d --hostname nginx.local nginx
c144f4e12f1b7a24f40f6d9585990e32370cf09e2a72d6981425d4db6648294c
MBP: user$ ping nginx.local
ping: cannot resolve nginx.local: Unknown host
```

**Comment by grachevko** [comment]
@Zakay what is your host OS? MacOS and Windows use virtual machine to run docker containers and you can't access directry to each containers by its ip. 
It work only for linux.

**Comment by Zakay** [comment]
I'm using macOS and running Docker from the Edge channel which isn't using a virtual machine. Should be now very similar to running it on linux.

**Comment by grachevko** [comment]
@Zakay run `docker inspect <container>` and find `IPAddress`, then try to ping. 
If you don't receive response, that's because docker on macos not exactly similar.

**Comment by Zakay** [comment]
Ah I see, docker doesn't setup a network bridge on macOS yet. Instead I'm now using an alias on my lo0 and let docker map ports on the alias instead. Hopefully this all gets solved soon!
